version: '3.3'

services:
  db:
    image: mariadb
    container_name: db-rezeptblog
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=geheimkey
    expose:
      - 3306
    volumes:
      - ./db:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-rezeptblog
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  flask:
    image: snickch/flask001:v2
    container_name: flask-rezeptblog
    restart: always
    ports:
        - 5000:5000
    volumes:
      - ./app:/app
    command: gunicorn -w 4 --bind 0.0.0.0:5000 wsgi:app
    depends_on:
      - "db"

    
  adminer:
    image: adminer
    container_name: adminer-rezeptblog
    ports:
     - 5050:8080
    environment:
     - ADMINER_DEFAULT_SERVER=db     
